# 1. Analyse des sources et Dictionnaire de données

Cette section automatise l'inventaire des fichiers sources et prépare le mapping des types de données pour la future base de données MySQL.

## 1.1 Chargement et Inspection des métadonnées
Nous parcourons le dossier data pour extraire :
* Le nom des fichiers sources.
* Les noms des colonnes présentes.
* Le typage détecté par Pandas (Dtype).
* Une suggestion de typage SQL optimisé (mapping automatique).

> **Note technique :** La fonction map_to_sql (Mapping) calcule dynamiquement la taille des VARCHAR en fonction de la longueur maximale des chaînes présentes dans chaque colonne, en ajoutant une marge de sécurité de 10 caractères.

In [251]:
import pandas as pd
import glob
import os

from IPython.display import display

path = 'data'
all_files = glob.glob(os.path.join(path , "*.xlsx"))
dictionnaire_final = []
dataframes = []

def map_to_sql(dtype, column_name, series):
    dtype_str = str(dtype)
    if "int" in dtype_str:
        return "BIGINT"
    elif "float" in dtype_str:
        return "DECIMAL(15,2)"
    elif "datetime" in dtype_str:
        return "DATETIME"
    else:
        max_len = series.astype(str).replace('nan', '').str.len().max()
        if pd.isna(max_len): max_len = 255
        return f"VARCHAR({int(max_len) + 10})"

for file in all_files:
    try:
        file_name = os.path.basename(file)
        df = pd.read_excel(file)

        df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

        for col in df.columns:
            dictionnaire_final.append({
                "Fichier Source": file_name,
                "Nom de la Colonne": col,
                "Type Python": df[col].dtype,
                "Type SQL suggéré": map_to_sql(df[col].dtype, col, df[col])
            })

    except Exception as e:
        print(f"Erreur sur {file}: {e}")

df_dict = pd.DataFrame(dictionnaire_final)

with pd.option_context('display.max_rows', None):
    display(df_dict)

,Fichier Source,Nom de la Colonne,Type Python,Type SQL suggéré
0,donnees_communes.xlsx,CODREG,int64,BIGINT
1,donnees_communes.xlsx,CODDEP,object,VARCHAR(13)
2,donnees_communes.xlsx,CODARR,float64,"DECIMAL(15,2)"
3,donnees_communes.xlsx,CODCAN,object,VARCHAR(12)
4,donnees_communes.xlsx,CODCOM,int64,BIGINT
5,donnees_communes.xlsx,COM,object,VARCHAR(55)
6,donnees_communes.xlsx,PMUN,int64,BIGINT
7,donnees_communes.xlsx,PCAP,int64,BIGINT
8,donnees_communes.xlsx,PTOT,int64,BIGINT
9,Valeurs-foncières.xlsx,Code service CH,float64,"DECIMAL(15,2)"
10,Valeurs-foncières.xlsx,Reference document,float64,"DECIMAL(15,2)"
11,Valeurs-foncières.xlsx,1 Articles CGI,float64,"DECIMAL(15,2)"
12,Valeurs-foncières.xlsx,2 Articles CGI,float64,"DECIMAL(15,2)"
13,Valeurs-foncières.xlsx,3 Articles CGI,float64,"DECIMAL(15,2)"
14,Valeurs-foncières.xlsx,4 Articles CGI,float64,"DECIMAL(15,2)"
15,Valeurs-foncières.xlsx,5 Articles CGI,float64,"DECIMAL(15,2)"
16,Valeurs-foncières.xlsx,No disposition,int64,BIGINT
17,Valeurs-foncières.xlsx,Date mutation,datetime64[us],DATETIME
18,Valeurs-foncières.xlsx,Nature mutation,str,VARCHAR(15)
19,Valeurs-foncières.xlsx,Valeur fonciere,float64,"DECIMAL(15,2)"
20,Valeurs-foncières.xlsx,No voie,float64,"DECIMAL(15,2)"
21,Valeurs-foncières.xlsx,B/T/Q,object,VARCHAR(11)
22,Valeurs-foncières.xlsx,Code type de voie,int64,BIGINT
23,Valeurs-foncières.xlsx,Type de voie,str,VARCHAR(14)
24,Valeurs-foncières.xlsx,Code voie,object,VARCHAR(14)
25,Valeurs-foncières.xlsx,Voie,object,VARCHAR(36)
26,Valeurs-foncières.xlsx,Code ID commune,int64,BIGINT
27,Valeurs-foncières.xlsx,Code postal,float64,"DECIMAL(15,2)"
28,Valeurs-foncières.xlsx,Commune,str,VARCHAR(40)
29,Valeurs-foncières.xlsx,Code departement,str,VARCHAR(13)
30,Valeurs-foncières.xlsx,Code commune,int64,BIGINT
31,Valeurs-foncières.xlsx,Préfixe de section,float64,"DECIMAL(15,2)"
32,Valeurs-foncières.xlsx,Section,str,VARCHAR(12)
33,Valeurs-foncières.xlsx,No plan,int64,BIGINT
34,Valeurs-foncières.xlsx,No Volume,float64,"DECIMAL(15,2)"
35,Valeurs-foncières.xlsx,1er lot,object,VARCHAR(17)
36,Valeurs-foncières.xlsx,Surface Carrez du 1er lot,float64,"DECIMAL(15,2)"
37,Valeurs-foncières.xlsx,2eme lot,float64,"DECIMAL(15,2)"
38,Valeurs-foncières.xlsx,Surface Carrez du 2eme lot,float64,"DECIMAL(15,2)"
39,Valeurs-foncières.xlsx,3eme lot,float64,"DECIMAL(15,2)"
40,Valeurs-foncières.xlsx,Surface Carrez du 3eme lot,float64,"DECIMAL(15,2)"
41,Valeurs-foncières.xlsx,4eme lot,float64,"DECIMAL(15,2)"
42,Valeurs-foncières.xlsx,Surface Carrez du 4eme lot,float64,"DECIMAL(15,2)"
43,Valeurs-foncières.xlsx,5eme lot,float64,"DECIMAL(15,2)"
44,Valeurs-foncières.xlsx,Surface Carrez du 5eme lot,float64,"DECIMAL(15,2)"
45,Valeurs-foncières.xlsx,Nombre de lots,int64,BIGINT
46,Valeurs-foncières.xlsx,Code type local,int64,BIGINT
47,Valeurs-foncières.xlsx,Type local,str,VARCHAR(21)
48,Valeurs-foncières.xlsx,Identifiant local,float64,"DECIMAL(15,2)"
49,Valeurs-foncières.xlsx,Surface reelle bati,int64,BIGINT
50,Valeurs-foncières.xlsx,Nombre pieces principales,int64,BIGINT
51,Valeurs-foncières.xlsx,Nature culture,str,VARCHAR(12)
52,Valeurs-foncières.xlsx,Nature culture speciale,str,VARCHAR(15)
53,Valeurs-foncières.xlsx,Surface terrain,float64,"DECIMAL(15,2)"
54,Valeurs-foncières.xlsx,Nom de l'acquereur,object,VARCHAR(27)
55,fr-esr-referentiel-geographique.xlsx,regrgp_nom,str,VARCHAR(23)
56,fr-esr-referentiel-geographique.xlsx,reg_nom,str,VARCHAR(36)
57,fr-esr-referentiel-geographique.xlsx,reg_nom_old,str,VARCHAR(36)
58,fr-esr-referentiel-geographique.xlsx,aca_nom,str,VARCHAR(34)
59,fr-esr-referentiel-geographique.xlsx,dep_nom,str,VARCHAR(53)
60,fr-esr-referentiel-geographique.xlsx,com_code,str,VARCHAR(16)
61,fr-esr-referentiel-geographique.xlsx,com_code1,object,VARCHAR(15)
62,fr-esr-referentiel-geographique.xlsx,com_code2,object,VARCHAR(15)
63,fr-esr-referentiel-geographique.xlsx,com_id,str,VARCHAR(16)
64,fr-esr-referentiel-geographique.xlsx,com_nom_maj_court,object,VARCHAR(42)
65,fr-esr-referentiel-geographique.xlsx,com_nom_maj,object,VARCHAR(42)
66,fr-esr-referentiel-geographique.xlsx,com_nom,object,VARCHAR(68)
67,fr-esr-referentiel-geographique.xlsx,uu_code,object,VARCHAR(15)
68,fr-esr-referentiel-geographique.xlsx,uu_id,str,VARCHAR(17)
69,fr-esr-referentiel-geographique.xlsx,uucr_id,str,VARCHAR(18)
70,fr-esr-referentiel-geographique.xlsx,uucr_nom,object,VARCHAR(60)
71,fr-esr-referentiel-geographique.xlsx,ze_id,str,VARCHAR(16)
72,fr-esr-referentiel-geographique.xlsx,dep_code,object,VARCHAR(13)
73,fr-esr-referentiel-geographique.xlsx,dep_id,str,VARCHAR(14)
74,fr-esr-referentiel-geographique.xlsx,dep_nom_num,str,VARCHAR(59)
75,fr-esr-referentiel-geographique.xlsx,dep_num_nom,str,VARCHAR(59)
76,fr-esr-referentiel-geographique.xlsx,aca_code,int64,BIGINT
77,fr-esr-referentiel-geographique.xlsx,aca_id,object,VARCHAR(13)
78,fr-esr-referentiel-geographique.xlsx,reg_code,int64,BIGINT
79,fr-esr-referentiel-geographique.xlsx,reg_id,str,VARCHAR(13)
80,fr-esr-referentiel-geographique.xlsx,reg_code_old,int64,BIGINT
81,fr-esr-referentiel-geographique.xlsx,reg_id_old,str,VARCHAR(13)
82,fr-esr-referentiel-geographique.xlsx,fd_id,str,VARCHAR(15)
83,fr-esr-referentiel-geographique.xlsx,fr_id,str,VARCHAR(14)
84,fr-esr-referentiel-geographique.xlsx,fe_id,str,VARCHAR(13)
85,fr-esr-referentiel-geographique.xlsx,uu_id_99,str,VARCHAR(17)
86,fr-esr-referentiel-geographique.xlsx,au_code,object,VARCHAR(15)
87,fr-esr-referentiel-geographique.xlsx,au_id,str,VARCHAR(17)
88,fr-esr-referentiel-geographique.xlsx,auc_id,str,VARCHAR(17)
89,fr-esr-referentiel-geographique.xlsx,auc_nom,object,VARCHAR(68)
90,fr-esr-referentiel-geographique.xlsx,uu_id_10,str,VARCHAR(17)
91,fr-esr-referentiel-geographique.xlsx,geolocalisation,str,VARCHAR(42)

## 1.2. Chargement des données
## Boucle d'itération et rendu des données
Cette étape permet de valider l'intégrité des fichiers XLSX et d'obtenir un premier aperçu visuel des structures.

* **Identification** : Nous affichons le nom du fichier pour confirmer la lecture.
* **Chargement** : Le contenu est chargé dans un **DataFrame**.
* **Rendu** : Nous utilisons `display(df.head())` pour générer un rendu visuel des 5 premières entrées.

## Gestion des exceptions (Error Handling)
En cas d'erreur lors de la lecture ou de l'affichage, un bloc `try...except` permet de capturer l'exception. Le script affiche alors le nom du fichier problématique ainsi que le message d'erreur associé pour faciliter le débogage.

In [229]:
path = 'data'
all_files = glob.glob(os.path.join(path , "*.xlsx"))
dataframes = []

for file in all_files:
    try:
        # En fixant sheet_name=0, tu garantis le type de retour 'DataFrame'
        df = pd.read_excel(file, sheet_name=0)
        if isinstance(df, pd.DataFrame):
            dataframes.append({"name": os.path.basename(file), "data": df})
        else:
            print(f"Format inattendu pour {file}")

    except Exception as e:
        print(f"Erreur sur {file}: {e}")

In [230]:
dataframes[0]['data']

,CODREG,CODDEP,CODARR,CODCAN,CODCOM,COM,PMUN,PCAP,PTOT
0,84,01,2.0,08,1,L'Abergement-Clémenciat,779,19,798
1,84,01,1.0,01,2,L'Abergement-de-Varey,256,1,257
2,84,01,1.0,01,4,Ambérieu-en-Bugey,14134,380,14514
3,84,01,2.0,22,5,Ambérieux-en-Dombes,1751,25,1776
4,84,01,1.0,04,6,Ambléon,112,6,118
...,...,...,...,...,...,...,...,...,...
34986,4,974,1.0,04,420,Sainte-Suzanne,24065,227,24292
34987,4,974,3.0,06,421,Salazie,7136,73,7209
34988,4,974,2.0,99,422,Le Tampon,79824,1009,80833
34989,4,974,4.0,14,423,Les Trois-Bassins,7015,91,7106
34990,4,974,2.0,16,424,Cilaos,5538,85,5623

In [231]:
dataframes[1]['data']

,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Nom de l'acquereur
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02,Vente,...,2,2,Appartement,NaN,48,3,NaN,NaN,NaN,GUIRAO
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02,Vente,...,2,2,Appartement,NaN,40,1,NaN,NaN,NaN,HARNOIS
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02,Vente,...,1,2,Appartement,NaN,82,3,NaN,NaN,NaN,ROGIER
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02,Vente,...,1,2,Appartement,NaN,27,1,NaN,NaN,NaN,BOCQUIER
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02,Vente,...,1,2,Appartement,NaN,47,2,NaN,NaN,NaN,GUILLOSSOU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30,Vente,...,1,2,Appartement,NaN,63,3,NaN,NaN,NaN,SAADOUN
34165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30,Vente,...,2,2,Appartement,NaN,66,3,NaN,NaN,NaN,GUECHI
34166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30,Vente,...,1,2,Appartement,NaN,63,3,NaN,NaN,NaN,PEDRON
34167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30,Vente,...,1,2,Appartement,NaN,77,4,NaN,NaN,NaN,HOUARD
34168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30,Vente,...,1,2,Appartement,NaN,84,4,NaN,NaN,NaN,BOIN

In [232]:
dataframes[2]['data']

,regrgp_nom,reg_nom,reg_nom_old,aca_nom,dep_nom,com_code,com_code1,com_code2,com_id,com_nom_maj_court,...,fd_id,fr_id,fe_id,uu_id_99,au_code,au_id,auc_id,auc_nom,uu_id_10,geolocalisation
0,Province,Auvergne-Rhône-Alpes,Rhône-Alpes,Lyon,Ain,01001,1001,1001,C01001,L ABERGEMENT CLEMENCIAT,...,FD111,FR11,FE1,SO,NaN,AU997,C01001,L'Abergement-Clémenciat,SO,"46.1534255214,4.92611354223"
1,Province,Auvergne-Rhône-Alpes,Rhône-Alpes,Lyon,Ain,01002,1002,1002,C01002,L ABERGEMENT DE VAREY,...,FD111,FR11,FE1,SO,2,AU002,AU002,Lyon,SO,"46.0091878776,5.42801696363"
2,Province,Auvergne-Rhône-Alpes,Rhône-Alpes,Lyon,Ain,01003,1003,1003,C01003,AMAREINS,...,FD111,FR11,FE1,SO,SO,SO,SO,SO,SO,NaN
3,Province,Auvergne-Rhône-Alpes,Rhône-Alpes,Lyon,Ain,01004,1004,1004,C01004,AMBERIEU EN BUGEY,...,FD111,FR11,FE1,UU01303,2,AU002,AU002,Lyon,UU01302,"45.9608475114,5.3729257777"
4,Province,Auvergne-Rhône-Alpes,Rhône-Alpes,Lyon,Ain,01005,1005,1005,C01005,AMBERIEUX EN DOMBES,...,FD111,FR11,FE1,SO,2,AU002,AU002,Lyon,SO,"45.9961799872,4.91227250796"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,Province,Corse,Corse,Corse,Haute-Corse,2B356,2B356,2B356,C2B356,ZALANA,...,FD111,FR11,FE1,SO,NaN,AU998,C2B356,Zalana,SO,"42.2536105064,9.38216254299"
38912,Province,Corse,Corse,Corse,Haute-Corse,2B361,2B361,2B361,C2B361,ZILIA,...,FD111,FR11,FE1,SO,391,AU391,AU391,Calvi,SO,"42.5186011027,8.90376320006"
38913,Province,Corse,Corse,Corse,Haute-Corse,2B364,2B364,2B364,C2B364,ZUANI,...,FD111,FR11,FE1,SO,NaN,AU998,C2B364,Zuani,SO,"42.264826425,9.34126627348"
38914,Province,Corse,Corse,Corse,Haute-Corse,2B365,2B365,2B365,C2B365,SAN GAVINO DI FIUMORBO,...,FD111,FR11,FE1,SO,NaN,AU000,C2B365,San-Gavino-di-Fiumorbo,SO,"41.9714498244,9.24775602009"
38915,Province,Corse,Corse,Corse,Haute-Corse,2B366,2B366,2B366,C2B366,CHISA,...,FD111,FR11,FE1,SO,NaN,AU000,C2B366,Chisa,SO,"41.9210089906,9.26560816948"

# 2. Création et Normalisation des entités
Cette section marque le passage des données brutes (fichiers plats) vers un modèle relationnel. Nous isolons chaque entité métier pour respecter les contraintes de clés étrangères (FK) et optimiser le stockage.

## 2.1 Entité : Région
La table region est notre premier référentiel de haut niveau.

**Opérations effectuées :**
* **Extraction :** Sélection des colonnes `reg_code` et `reg_nom`.
* **Nettoyage :** Suppression des doublons `drop_duplicates` et des valeurs nulles `dropna`.
* **Normalisation :** Renommage en snake_case pour la compatibilité SQL.
    * Utilisation de `.zfill(2)` sur le code région pour garantir un formatage `VARCHAR(2)` constant (ex: "1" devient "01").

In [233]:
df_region = dataframes[2]['data'][['reg_code', 'reg_nom']].drop_duplicates().dropna()
df_region.columns = ['code_region', 'nom_region']
df_region['code_region'] = df_region['code_region'].astype(str).str.zfill(2)

display(df_region)

      code_region                  nom_region
0              84        Auvergne-Rhône-Alpes
459            32             Hauts-de-France
1614           93  Provence-Alpes-Côte d'Azur
2555           44                   Grand Est
3058           76                   Occitanie
4728           28                   Normandie
5761           75          Nouvelle-Aquitaine
6672           24         Centre-Val de Loire
7251           27     Bourgogne-Franche-Comté
7968           53                    Bretagne
17259          52            Pays de la Loire
31754          11               Ile-de-France
38306          01                  Guadeloupe
38340          02                  Martinique
38374          03                      Guyane
38400          04                  La Réunion
38424          00   Collectivités d'outre-mer
38426          06                     Mayotte
38550          94                       Corse

## 2.2 Entité : Département
Cette table assure la liaison entre les régions et les communes. Elle introduit une dépendance fonctionnelle `Foreign Key` vers l'entité `region`.

**Opérations effectuées :**
* **Extraction :** Sélection du trio `dep_code`, `dep_nom` et `reg_code` (clé de liaison).
* **Nettoyage :** Suppression des doublons et des lignes incomplètes.
* **Standardisation :**
    * `code_region` : Formaté sur 2 caractères `zfill(2)` pour correspondre à la table parente.
    * `code_departement` : Formaté sur 3 caractères `zfill(3)`.

> **Note métier :** Le formatage à 3 caractères pour le département (ex: 001 pour l'Ain) est une précaution pour inclure les départements d'Outre-mer et maintenir une longueur fixe en base de données (VARCHAR(3)).

In [234]:
df_departement = dataframes[2]['data'][['dep_code', 'dep_nom', 'reg_code']].drop_duplicates().dropna()
df_departement.columns = ['code_departement','nom_departement','code_region']
df_departement['code_region'] = df_departement['code_region'].astype(str).str.zfill(2)
df_departement['code_departement'] = df_departement['code_departement'].astype(str).str.zfill(3)

display(df_departement)

      code_departement          nom_departement code_region
0                  001                      Ain          84
459                002                    Aisne          32
1293               003                   Allier          84
1614               004  Alpes-de-Haute-Provence          93
1859               005             Hautes-Alpes          93
...                ...                      ...         ...
38467              987      Polynésie Française          00
38516              988       Nouvelle-Calédonie          00
38549              989        Ile de Clipperton          00
38550              02A             Corse-du-Sud          94
38677              02B              Haute-Corse          94

[109 rows x 3 columns]

## 2.3 Entité : Commune (Enrichissement et Géolocalisation)
La création de la table `commune` est le résultat d'une jointure entre trois sources de données distinctes afin de consolider l'identité, le code postal et les coordonnées GPS.

### Processus de fusion (Merging strategy)
1. **Identité :** Extraction du code INSEE (Département + Commune) et du nom de la commune.
2. **Code Postal :** Récupération du code postal via une jointure sur les codes composants.
3. **Géolocalisation :** Intégration des données de positionnement (Latitude/Longitude).

### Nettoyage et Transformation
1. **Calcul du Code INSEE :** Création de la clé `full_insee` par concaténation (`CODDEP` + `CODCOM`) pour obtenir un identifiant unique standardisé à 5 caractères.
2. **Parsing Géographique :** Décomposition de la colonne `geolocalisation` (format chaîne "Lat, Long") en deux colonnes numériques distinctes via `.str.split()`.
3. **Normalisation finale :** `code_postal` : Forcé à 5 caractères `zfill(5)`.
    * `code_departement` : Aligné sur 3 caractères pour garantir la cohérence avec la table departement.

In [235]:
df_identite = dataframes[0]['data'][['CODCOM', 'CODDEP', 'COM']].drop_duplicates().dropna()
df_identite['CODDEP'] = df_identite['CODDEP'].astype(str).str.strip().str.zfill(2)
df_identite['CODCOM'] = df_identite['CODCOM'].astype(str).str.strip().str.zfill(3)

df_postal = dataframes[1]['data'][['Code commune', 'Code departement', 'Code postal']].drop_duplicates().dropna()
df_postal['Code departement'] = pd.to_numeric(df_postal['Code departement'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(2)
df_postal['Code commune'] = pd.to_numeric(df_postal['Code commune'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(3)

df_geoloc = dataframes[2]['data'][['com_code', 'geolocalisation']].drop_duplicates().dropna()
df_geoloc['com_code'] = df_geoloc['com_code'].astype(str).str.strip().str.zfill(5)

df_temp = pd.merge(
    df_identite,
    df_postal,
    left_on=['CODDEP', 'CODCOM'],
    right_on=['Code departement', 'Code commune'],
    how='left'
)

df_temp['full_insee'] = df_temp['CODDEP'] + df_temp['CODCOM']

df_commune = pd.merge(
    df_temp,
    df_geoloc,
    left_on='full_insee',
    right_on='com_code',
    how='left'
)

coords = df_commune['geolocalisation'].str.split(',', expand=True)
df_commune['latitude'] = pd.to_numeric(coords[0], errors='coerce')
df_commune['longitude'] = pd.to_numeric(coords[1], errors='coerce')

df_commune['Code postal'] = pd.to_numeric(df_commune['Code postal'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(5)

df_commune_final = df_commune[['full_insee', 'CODDEP', 'COM', 'Code postal', 'latitude', 'longitude']].copy()
df_commune_final.columns = ['code_commune', 'code_departement', 'nom_commune', 'code_postal', 'latitude', 'longitude']
df_commune_final['code_departement'] = df_commune_final['code_departement'].astype(str).str.strip().str.zfill(3)
display(df_commune_final.head())

,code_commune,code_departement,nom_commune,code_postal,latitude,longitude
0,01001,001,L'Abergement-Clémenciat,00000,46.153426,4.926114
1,01002,001,L'Abergement-de-Varey,00000,46.009188,5.428017
2,01004,001,Ambérieu-en-Bugey,01500,45.960848,5.372926
3,01005,001,Ambérieux-en-Dombes,00000,45.996180,4.912273
4,01006,001,Ambléon,00000,45.749499,5.594320

## 2.4 Entité : Type de Voie (Référentiel)
Cette table sert de dictionnaire pour les types de voies (Rue, Avenue, Boulevard, etc.). Au lieu de stocker le texte complet dans chaque ligne d'adresse, nous utilisons un identifiant numérique (code_type_voie).

**Opérations effectuées :**
* **Extraction :** Isolation du couple code/libellé depuis les données de transaction.
* **Dédoublonnage :** Utilisation de .drop_duplicates() pour garantir qu'un code ne pointe que vers une seule description.
* **Nettoyage :** Suppression des entrées nulles pour assurer l'intégrité de la table de référence.

> **Avantage technique :** Cette structure réduit considérablement la taille de la base de données et facilite la création de listes déroulantes dans une interface utilisateur (UI).

In [236]:
df_type_voie = dataframes[1]['data'][['Code type de voie', 'Type de voie']].drop_duplicates().dropna()
df_type_voie.columns = ['code_type_voie', 'type_voie']
display(df_type_voie)

       code_type_voie type_voie
0                   0       RUE
1                  15        BD
3                   3       RTE
4                  18       RES
6                   1        AV
...               ...       ...
19285              77      PIST
21652              54       PRV
22135              70       GAL
23996              60      PLAN
27506              26      ILOT

[79 rows x 2 columns]

## 2.5 Entité : Adresse
Cette cellule génère la table pivot adresse. Elle centralise les informations de localisation précises et permet de lier les biens immobiliers à leur emplacement géographique.

### Transformation et Nettoyage
* **Clé de liaison `Commune`** : Reconstruction du code INSEE par concaténation du département et de la commune `zfill` pour assurer la jointure avec la table commune.
* **Typage numérique :** Conversion forcée des codes de voie et numéros en entiers pour garantir la propreté des indexations SQL.
* **Gestion des compléments `B/T/Q` :** Nettoyage des valeurs `NaN` remplacées par `None` (équivalent du `NULL` en SQL).
* **Troncation :** Limitation du nom de la voie à 50 caractères pour respecter la contrainte `VARCHAR(50)` du schéma SQL.

### Création de la Clé Primaire (Surrogate Key)
* Contrairement aux référentiels précédents, l'adresse ne possède pas d'identifiant unique naturel dans le fichier source.
* **Dédoublonnage :** `drop_duplicates()` permet d'isoler chaque adresse unique.

> **Auto-incrémentation manuelle :** Utilisation de l'index (.index + 1) pour générer id_adresse, qui servira de clé primaire (PK) et sera référencée par la table bien.

In [237]:
df_adresse = dataframes[1]['data'][[
    'Code type de voie', 'Code voie', 'Voie', 'B/T/Q', 'Code departement', 'Code commune'
]].copy()

df_adresse['code_commune'] = (
    pd.to_numeric(df_adresse['Code departement'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(2) +
    pd.to_numeric(df_adresse['Code commune'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(3)
)

df_adresse['numero_voie'] = pd.to_numeric(df_adresse['Code voie'], errors='coerce').fillna(0).astype(int)
df_adresse['code_type_voie'] = pd.to_numeric(df_adresse['Code type de voie'], errors='coerce').fillna(0).astype(int)
df_adresse['nom_voie'] = df_adresse['Voie'].astype(str).str[:50]
df_adresse['b_t_q'] = df_adresse['B/T/Q'].astype(str).replace('nan', None)

df_adresse_final = df_adresse[['code_commune', 'code_type_voie', 'numero_voie', 'nom_voie', 'b_t_q']].drop_duplicates()

display(df_adresse_final.head())

df_adresse_final = df_adresse_final.reset_index(drop=True)

df_adresse_final['id_adresse'] = df_adresse_final.index + 1

display(df_adresse_final.head())

,code_commune,code_type_voie,numero_voie,nom_voie,b_t_q,id_adresse
0,01103,0,20,DU CHATEAU,NaN,1
1,06004,15,1000,EDOUARD BAUDOIN,NaN,2
2,06088,0,3975,MARCEAU,B,3
3,06123,3,1011,DES VESPINS RN7,NaN,4
4,13005,18,0,LES ARPEGES BD DES ABA,NaN,5

## 2.6 Entité : Type de Local (Référentiel)
Cette table de référence répertorie les différentes catégories de biens immobiliers (Maison, Appartement, Dépendance, Local industriel). Elle permet de classifier les biens de la table bien via une clé étrangère numérique.

**Opérations effectuées :**
* **Extraction :** Sélection du couple `Code type local` et `Type local`.
* **Dédoublonnage :** Garantie de l'unicité de chaque type de bien pour servir de base de données de référence.
* **Typage SQL :** Préparation pour une colonne `TINYINT` ou `INT` en base de données, optimisant les performances de filtrage et de groupement.

> **Note métier :** La séparation de cette donnée permet d'assurer l'intégrité du domaine (on ne peut pas insérer un type de local qui n'existe pas dans ce référentiel).

In [238]:
df_type_local = dataframes[1]['data'][['Code type local', 'Type local']].drop_duplicates().dropna()
df_type_local.columns = ['code_type_local', 'type_local']
display(df_type_local)

   code_type_local   type_local
0                2  Appartement
9                1       Maison

## 2.7 Entité : Bien (Caractéristiques techniques et Liaison)
Cette cellule génère la table bien, qui regroupe les informations descriptives des propriétés. La complexité ici réside dans la récupération de la clé étrangère `id_adresse` créée à l'étape précédente.

### Stratégie de liaison (Mapping)
* **Préparation des clés naturelles :** Comme pour la table `adresse`, nous reconstruisons les clés composites (`code commune`, `numéro`, `type de voie`) pour servir de base à la jointure.
* **Jointure :** Nous effectuons un `pd.merge` de type `left` avec `df_adresse_final`. Cela permet de récupérer le `id_adresse` correspondant à chaque ligne de bien en fonction de sa localisation.
* **Nettoyage post-jointure :** Nous supprimons les colonnes de jointure devenues inutiles.
Nous filtrons les lignes sans adresse valide via `dropna(subset=['id_adresse'])` pour garantir l'intégrité référentielle (pas de bien sans adresse).

### Création de la Clé Primaire
* **Clé Substituée :** De la même manière que pour l'adresse, nous utilisons l'index du DataFrame (index + 1) pour générer une clé primaire unique id_bien.
* **Renommage :** Les colonnes sont renommées en snake_case (ex: `surface_carre`, `nombre_pieces`) pour une intégration fluide dans le schéma MySQL.

In [239]:
df_bien = dataframes[1]['data'][[
    'Nombre de lots', 'Code type local', 'Surface reelle bati',
    'Nombre pieces principales', 'Section', 'No plan', 'Surface Carrez du 1er lot',
    'Code type de voie', 'Code voie', 'Voie', 'B/T/Q', 'Code departement', 'Code commune' # Colonnes de lien
]].copy()

# 2. On prépare les clés de jointure dans df_bien pour qu'elles matchent df_adresse_final
df_bien['code_commune'] = (
    pd.to_numeric(df_bien['Code departement'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(2) +
    pd.to_numeric(df_bien['Code commune'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(3)
)
df_bien['numero_voie'] = pd.to_numeric(df_bien['Code voie'], errors='coerce').fillna(0).astype(int)
df_bien['code_type_voie'] = pd.to_numeric(df_bien['Code type de voie'], errors='coerce').fillna(0).astype(int)
df_bien['nom_voie'] = df_bien['Voie'].astype(str).str[:50]
df_bien['b_t_q'] = df_bien['B/T/Q'].astype(str).replace('nan', None)

# 3. JOINTURE : On récupère l'id_adresse depuis df_adresse_final
df_bien = pd.merge(
    df_bien,
    df_adresse_final[['id_adresse', 'code_commune', 'code_type_voie', 'numero_voie', 'nom_voie', 'b_t_q']],
    on=['code_commune', 'code_type_voie', 'numero_voie', 'nom_voie', 'b_t_q'],
    how='left'
)

# 4. Sélection finale et renommage (On supprime les colonnes de lien inutiles maintenant)
df_bien_final = df_bien[[
    'id_adresse', 'Nombre de lots', 'Code type local', 'Surface reelle bati',
    'Nombre pieces principales', 'Section', 'No plan', 'Surface Carrez du 1er lot'
]].drop_duplicates().dropna(subset=['id_adresse'])

df_bien_final.columns = [
    'id_adresse', 'nombre_lots', 'code_type_local', 'surface_reelle_bati',
    'nombre_pieces', 'section', 'numero_plan', 'surface_carre'
]

display(df_bien_final.head())

df_bien_final = df_bien_final.reset_index(drop=True)

# On crée la colonne id_adresse (on commence à 1 pour simuler SQL)
df_bien_final['id_bien'] = df_bien_final.index + 1

display(df_bien_final.head())

,id_adresse,nombre_lots,code_type_local,surface_reelle_bati,nombre_pieces,section,numero_plan,surface_carre,id_bien
0,1,2,2,48,3,A,302,48.22,1
1,2,2,2,40,1,CP,186,39.11,2
2,3,1,2,82,3,LS,169,80.25,3
3,4,1,2,27,1,AO,348,27.51,4
4,5,1,2,47,2,AW,224,47.33,5

## 2.8 Entité : Transaction (Table de Faits)
La table transaction clôture la phase de normalisation. Elle enregistre les données de ventes en les rattachant aux biens immobiliers via la clé étrangère `id_bien`.

### Récupération de l'identifiant du bien (Data Alignment)
Pour lier une vente à son bien, nous réalisons une jointure `pd.merge` sur l'ensemble des caractéristiques techniques :
* **Clés de jointure :** `Nombre de lots`, `type local`, `surfaces (réelle et Carrez)`, `nombre de pièces` et références cadastrales (`section` / `plan`).
* **Finalité :** Récupérer le `id_bien` généré à l'étape précédente pour garantir l'intégrité référentielle entre l'acte de vente et l'objet physique vendu.

### Nettoyage et Formatage Temporel
* **Typage Date :** Conversion de la colonne `date_mutation` au format datetime pour permettre des analyses temporelles (ventes par mois/année) en SQL.
* **Typage Monétaire :** Préparation de la colonne `valeur_fonciere` (souvent convertie en float ou decimal en base de données).
* **Sélection :** Seules les colonnes essentielles à la transaction sont conservées pour respecter la structure de la table finale.

In [240]:
df_transaction = dataframes[1]['data'][[
    'Date mutation', 'Valeur fonciere', "Nom de l'acquereur",
    'Nombre de lots', 'Code type local', 'Surface reelle bati',
    'Nombre pieces principales', 'Section', 'No plan', 'Surface Carrez du 1er lot'
]].copy()

df_transaction = pd.merge(
    df_transaction,
    df_bien_final,
    left_on=['Nombre de lots', 'Code type local', 'Surface reelle bati',
             'Nombre pieces principales', 'Section', 'No plan', 'Surface Carrez du 1er lot'],
    right_on=['nombre_lots', 'code_type_local', 'surface_reelle_bati',
              'nombre_pieces', 'section', 'numero_plan', 'surface_carre'],
    how='left'
)

df_transaction_final = df_transaction[[
    'id_bien', 'Date mutation', 'Valeur fonciere', "Nom de l'acquereur"
]].copy()

df_transaction_final.columns = ['id_bien', 'date_mutation', 'valeur_fonciere', 'nom_acquereur']

df_transaction_final['date_mutation'] = pd.to_datetime(df_transaction_final['date_mutation'], errors='coerce')

display(df_transaction_final.head())

df_bien_final = df_bien_final.reset_index(drop=True)

df_bien_final['id_bien'] = df_bien_final.index + 1

display(df_bien_final.head())

,id_adresse,nombre_lots,code_type_local,surface_reelle_bati,nombre_pieces,section,numero_plan,surface_carre,id_bien
0,1,2,2,48,3,A,302,48.22,1
1,2,2,2,40,1,CP,186,39.11,2
2,3,1,2,82,3,LS,169,80.25,3
3,4,1,2,27,1,AO,348,27.51,4
4,5,1,2,47,2,AW,224,47.33,5

# 3. Sécurisation de l'Intégrité Référentielle
Avant de procéder à l'injection des données dans MySQL, il est impératif de garantir que les contraintes de clés primaires sont respectées. Une clé primaire doit être unique et non nulle.

## 3.1 Nettoyage de la table Commune
La table commune utilise le code INSEE comme identifiant unique. Toute erreur d'unicité ici bloquerait l'importation de l'ensemble du jeu de données.
**Mesures de sécurité appliquées :**
* **Unicité :** Suppression de tout doublon potentiel sur la colonne code_commune. Cela garantit qu'une seule ligne existe pour chaque commune française.
* **Non-nullité :** Élimination des lignes où le code_commune est manquant. En SQL, une clé primaire ne peut jamais être NULL.

> **Note technique :** Ces opérations de nettoyage "pré-insertion" permettent d'éviter les erreurs d'intégrité de type 1062 Duplicate entry lors de l'exécution du script d'import.

In [241]:
df_commune_final = df_commune_final.drop_duplicates(subset=['code_commune'])
df_commune_final = df_commune_final.dropna(subset=['code_commune'])

# 4. Ingestion des données dans MySQL (Phase Load)
Cette cellule orchestre le chargement final des DataFrames transformés vers la base de données relationnelle p03. Elle intègre des mécanismes de sécurité pour gérer les contraintes d'intégrité de MySQL.

## 4.1 Réinitialisation et Purge (Reset)
Afin d'éviter les erreurs de doublons lors des tests successifs, nous procédons à une purge complète des tables.
`SET FOREIGN_KEY_CHECKS = 0` : Désactivation temporaire des contraintes pour permettre le vidage des tables parentes et enfants sans erreur de dépendance.
`TRUNCATE` : Réinitialisation des tables et des compteurs d'auto-incrément.

## 4.2 Alignement des types et Filtrage final
Avant l'insertion, un dernier contrôle de cohérence est effectué :
* **Cast Numérique :** Conversion forcée des identifiants en entiers (int) pour correspondre au typage de la base de données.
* **Gestion des Orphelins :** Utilisation de `.isin()` pour filtrer les adresses dont le code commune ou le type de voie n'existerait pas dans les référentiels parents. Cela prévient les erreurs de clés étrangères.

## 4.3 Injection Séquentielle
L'ordre d'insertion respecte strictement la hiérarchie relationnelle pour satisfaire les contraintes de clés étrangères :
* **Référentiels indépendants :** `region`, `type_voie`, `type_local`.
* **Entités dépendantes :** `commune`, `adresse`, `bien`, `transaction`.

In [242]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:3101@localhost:3306/p03")

with engine.connect() as connection:
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 0;"))
    # Liste de toutes tes tables
    for t in ['transaction', 'bien', 'adresse', 'commune', 'departement', 'region', 'type_voie', 'type_local']:
        connection.execute(text(f"TRUNCATE TABLE {t};"))
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 1;"))
    connection.commit()


df_adresse_for_sql = df_adresse_final[['code_commune', 'code_type_voie', 'numero_voie', 'nom_voie', 'b_t_q']]
df_bien_for_sql = df_bien_final[[
    'id_adresse', 'nombre_lots', 'code_type_local', 'surface_reelle_bati',
    'nombre_pieces', 'section', 'numero_plan', 'surface_carre'
]]
df_type_voie['code_type_voie'] = pd.to_numeric(df_type_voie['code_type_voie'], errors='coerce').fillna(0).astype(int)
df_adresse_for_sql['code_type_voie'] = pd.to_numeric(df_adresse_for_sql['code_type_voie'], errors='coerce').fillna(0).astype(int)

df_type_voie['code_type_voie'] = pd.to_numeric(df_type_voie['code_type_voie'], errors='coerce').fillna(0).astype(int)
df_adresse_for_sql['code_type_voie'] = pd.to_numeric(df_adresse_for_sql['code_type_voie'], errors='coerce').fillna(0).astype(int)

df_type_voie = df_type_voie.drop_duplicates(subset=['code_type_voie'])

df_adresse_for_sql = df_adresse_for_sql[
    df_adresse_for_sql['code_type_voie'].isin(df_type_voie['code_type_voie']) &
    df_adresse_for_sql['code_commune'].isin(df_commune_final['code_commune'])
]
try:
    df_region.to_sql('region', con=engine, if_exists='append', index=False)
    df_departement.to_sql('departement', con=engine, if_exists='append', index=False)
    df_commune_final.to_sql('commune', con=engine, if_exists='append', index=False)
    df_type_voie.to_sql('type_voie', con=engine, if_exists='append', index=False)
    df_adresse_for_sql.to_sql('adresse', con=engine, if_exists='append', index=False)
    df_type_local.to_sql('type_local', con=engine, if_exists='append', index=False)
except Exception as e:
    print(f"❌ Échec de l'insertion : {e}")

# 4.4 Phase de Synchronisation Post-Insertion
Cette section est critique : elle assure la réconciliation entre les données transformées dans le Notebook et les identifiants réels générés par le moteur MySQL.

## 4.4.1 Pourquoi recalculer les liaisons ?
Lors de l'étape précédente, la table adresse a été injectée en base. MySQL a alors attribué de nouveaux identifiants `id_adresse` via son mécanisme d'auto-incrément. Nos DataFrames locaux (`df_bien`) possèdent des IDs théoriques qui peuvent différer de la réalité en base (en cas de doublons supprimés ou de réinitialisation de table).

Nous procédons donc à un "Recalcul de Synchronisation" :
* **Extraction de la "Source of Truth" :** On récupère via un `SELECT` les adresses telles qu'elles existent physiquement en base de données.
* **Re-mappage des Biens :** On effectue une nouvelle jointure entre nos données de biens et les IDs officiels de la base.
* **Sécurisation des Clés Étrangères (FK) :** L'utilisation d'un `inner join` ici garantit qu'aucun bien ne sera inséré s'il pointe vers une adresse qui n'a pas été validée par MySQL.

> **Impact technique :** Cette étape transforme nos données "volatiles" en données "persistantes" prêtes pour l'analyse SQL finale.

In [244]:
df_adresse_mysql = pd.read_sql("SELECT id_adresse, code_commune, code_type_voie, numero_voie, nom_voie, b_t_q FROM adresse", con=engine)

# 2. Création du DataFrame Bien avec renommage IMMÉDIAT
df_bien = dataframes[1]['data'][[
    'Nombre de lots', 'Code type local', 'Surface reelle bati',
    'Nombre pieces principales', 'Section', 'No plan', 'Surface Carrez du 1er lot',
    'Code type de voie', 'Code voie', 'Voie', 'B/T/Q', 'Code departement', 'Code commune'
]].copy()

# On renomme tout de suite pour éviter les KeyError plus tard
df_bien.columns = [
    'nombre_lots', 'code_type_local', 'surface_reelle_bati',
    'nombre_pieces', 'section', 'numero_plan', 'surface_carre',
    'c_type_v_temp', 'c_v_temp', 'v_temp', 'btq_temp', 'dep_temp', 'com_temp'
]

# 3. Création des clés de jointure sur df_bien (doivent matcher df_adresse_mysql)
df_bien['code_commune'] = (
    pd.to_numeric(df_bien['dep_temp'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(2) +
    pd.to_numeric(df_bien['com_temp'], errors='coerce').fillna(0).astype(int).astype(str).str.zfill(3)
)
df_bien['numero_voie'] = pd.to_numeric(df_bien['c_v_temp'], errors='coerce').fillna(0).astype(int)
df_bien['code_type_voie'] = pd.to_numeric(df_bien['c_type_v_temp'], errors='coerce').fillna(0).astype(int)
df_bien['nom_voie'] = df_bien['v_temp'].astype(str).str.strip().str[:50]
df_bien['b_t_q'] = df_bien['btq_temp'].astype(str).replace('nan', None)

# 4. JOINTURE avec les vrais IDs de la base de données
df_bien_fixed = pd.merge(
    df_bien,
    df_adresse_mysql,
    on=['code_commune', 'code_type_voie', 'numero_voie', 'nom_voie', 'b_t_q'],
    how='inner' # On ne garde que les biens dont l'adresse existe en BDD
)

# 5. Sélection finale (Maintenant 'nombre_lots' etc existent bien !)
df_bien_for_sql = df_bien_fixed[[
    'id_adresse', 'nombre_lots', 'code_type_local', 'surface_reelle_bati',
    'nombre_pieces', 'section', 'numero_plan', 'surface_carre'
]].drop_duplicates()

display(df_bien_for_sql.head())

,id_adresse,nombre_lots,code_type_local,surface_reelle_bati,nombre_pieces,section,numero_plan,surface_carre
0,1,2,2,48,3,A,302,48.22
1,2,2,2,40,1,CP,186,39.11
2,3,1,2,82,3,LS,169,80.25
3,4,1,2,27,1,AO,348,27.51
4,5,1,2,47,2,AW,224,47.33

# 4.5 Ingestion des entités liées (Bien & Transaction)
Cette étape finalise le chargement de la base de données en insérant les données de l'entité bien. C'est ici que la structure relationnelle est la plus sensible aux contraintes d'intégrité.

## 4.5.1 Nettoyage sélectif et insertion
Afin de garantir une insertion propre, nous appliquons une stratégie de purge ciblée :
* **Isolation des contraintes :** On désactive temporairement les `FOREIGN_KEY_CHECKS` pour vider les tables bien et transaction. Cela évite les erreurs de blocage lors du `TRUNCATE`.
* **Injection du DataFrame synchronisé :** On insère le DataFrame `df_bien_for_sql` qui contient les vrais IDs d'adresses récupérés à l'étape précédente.

> **Note sur l'intégrité :** En utilisant `if_exists='append`, nous ajoutons les données à la structure existante définie dans le schéma SQL, tout en laissant MySQL gérer l'auto-incrément pour la colonne `id_bien`.

In [245]:
with engine.connect() as connection:
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 0;"))
    connection.execute(text("TRUNCATE TABLE transaction;"))
    connection.execute(text("TRUNCATE TABLE bien;"))
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 1;"))
    connection.commit()

try:
    # On n'insère QUE les tables qui manquent
    df_bien_for_sql.to_sql('bien', con=engine, if_exists='append', index=False)

    print("✅ Transfert réussi !")
except Exception as e:
    print(f"❌ Erreur : {e}")

✅ Transfert réussi !

## 4.6 Synchronisation Finale : Récupération des IDs Biens
Cette étape est le dernier rempart avant l'analyse. Elle consiste à lier les transactions financières aux identifiants uniques `id_bien` générés par MySQL lors de l'étape précédente.

### Méthodologie de réalignement (Data Alignment)
* **Extraction des Clés Primaires :** Nous interrogeons la table bien en base pour récupérer les couples [Caractéristiques Techniques / id_bien].
* **Jointure de Sécurité `Inner Join` :** En fusionnant les données sources avec les données SQL, nous éliminons automatiquement les transactions "orphelines" qui pointeraient vers des biens n'ayant pas pu être insérés (ex: données corrompues ou incomplètes).
* **Sanitisation financière :** Nettoyage : Suppression des lignes sans valeur_fonciere (contrainte NOT NULL en SQL).
    * **Casting :** Conversion de la `date_mutation` en format temporel standard pour permettre les agrégations par période (Quarter/Year) en SQL.

> **Note technique :** L'utilisation des colonnes techniques (`section`, `numero_plan`, etc.) comme clés de jointure garantit qu'une transaction est rattachée à la bonne unité foncière, même dans des copropriétés complexes.

In [246]:
# 1. On récupère les BIENS réellement présents en BDD
df_bien_mysql = pd.read_sql("SELECT id_bien, nombre_lots, code_type_local, surface_reelle_bati, section, numero_plan FROM bien", con=engine)

# 2. On repart des données sources pour les transactions (pour avoir les colonnes de lien)
df_trans_source = dataframes[1]['data'][[
    'Date mutation', 'Valeur fonciere', "Nom de l'acquereur",
    'Nombre de lots', 'Code type local', 'Surface reelle bati',
    'Section', 'No plan'
]].copy()

# Renommage pour matcher df_bien_mysql
df_trans_source.columns = [
    'date_mutation', 'valeur_fonciere', 'nom_acquereur',
    'nombre_lots', 'code_type_local', 'surface_reelle_bati', 'section', 'numero_plan'
]

# 3. JOINTURE : On récupère le VRAI id_bien généré par MySQL
df_transaction_fixed = pd.merge(
    df_trans_source,
    df_bien_mysql,
    on=['nombre_lots', 'code_type_local', 'surface_reelle_bati', 'section', 'numero_plan'],
    how='inner' # On ne garde que les transactions dont le bien existe en BDD
)

# 4. Nettoyage final (Types et suppression des NaNs sur valeur_fonciere)
df_transaction_for_sql = df_transaction_fixed[['id_bien', 'date_mutation', 'valeur_fonciere', 'nom_acquereur']].copy()
df_transaction_for_sql['valeur_fonciere'] = pd.to_numeric(df_transaction_for_sql['valeur_fonciere'], errors='coerce')
df_transaction_for_sql = df_transaction_for_sql.dropna(subset=['valeur_fonciere'])
df_transaction_for_sql['date_mutation'] = pd.to_datetime(df_transaction_for_sql['date_mutation'])

display(df_transaction_for_sql.head())

   id_bien date_mutation  valeur_fonciere nom_acquereur
0        1    2020-01-02         165000.0        GUIRAO
1        2    2020-01-02         355680.0       HARNOIS
2        3    2020-01-02         229500.0        ROGIER
3        4    2020-01-02         125000.0      BOCQUIER
4        5    2020-01-02          90000.0    GUILLOSSOU

## 4.7 Injection Finale : Table des Transactions
Cette étape marque l'achèvement du chargement de la base de données p03. La table transaction est la table de faits centrale qui lie toutes les autres entités entre elles.

### Sécurisation de l'insertion
* **Gestion des conflits :** Comme pour les étapes précédentes, nous utilisons un `TRUNCATE` (plus performant qu'un `DELETE`) après avoir temporairement levé les vérifications de clés étrangères. Cela permet de repartir sur une table vide et d'éviter toute erreur de duplication si le script est relancé.
* **Persistance des données :** L'utilisation de `to_sql` avec le paramètre `if_exists='append'` transfère le DataFrame finalisé vers MySQL.

### Validation du Pipeline
Le message de confirmation "TRANSFERT RÉUSSI" n'apparaît que si l'intégralité des contraintes SQL (Not Null, Foreign Keys, Types de données) a été respectée, validant ainsi la qualité du nettoyage effectué en amont.

In [247]:
from sqlalchemy import text

with engine.connect() as connection:
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 0;"))
    connection.execute(text("TRUNCATE TABLE transaction;"))
    connection.execute(text("SET FOREIGN_KEY_CHECKS = 1;"))
    connection.commit()

try:
    df_transaction_for_sql.to_sql('transaction', con=engine, if_exists='append', index=False)
    print("✅ TRANSFERT RÉUSSI : La base p03 est totalement remplie !")
except Exception as e:
    print(f"❌ Erreur finale : {e}")

✅ TRANSFERT RÉUSSI : La base p03 est totalement remplie !

# 5. Analyses Statistiques et Extractions SQL
Une fois la base de données chargée et intègre, nous pouvons exploiter les données pour répondre aux besoins d'analyse. Cette section utilise des requêtes SQL complexes pour transformer les données brutes en indicateurs clés (KPIs).

## 5.1 Analyse du prix moyen au m² par département
Cette requête permet d'identifier les zones géographiques les plus onéreuses en calculant le ratio entre la valeur foncière et la surface bâtie.

**Décomposition de la requête SQL :**
* `SELECT` : On sélectionne le nom du département et on calcule la moyenne `AVG` du prix au m². La fonction `ROUND(..., 2)` est utilisée pour limiter le résultat à deux décimales pour une meilleure lisibilité.
* `JOIN` (Les jointures) :
    * On part de la table transaction (`t`).
    * On remonte vers le bien (`b`) pour avoir la surface.
    * On passe par adresse (`a`) et commune (`c`) pour faire le pont géographique.
    * On termine sur departement (`d`) pour récupérer le nom en clair.
* `GROUP BY` : On regroupe les calculs par département afin d'obtenir une seule ligne par entité géographique.
* `ORDER BY ... DESC` : On trie les résultats du plus cher au moins cher pour mettre en évidence les disparités du marché.

In [252]:
query = """
SELECT
    d.nom_departement AS Departement,
    ROUND(AVG(t.valeur_fonciere / b.surface_reelle_bati), 2) AS Prix_Moyen_m2
FROM transaction AS t
JOIN bien AS b ON t.id_bien = b.id_bien
JOIN adresse AS a ON b.id_adresse = a.id_adresse
JOIN commune AS c ON a.code_commune = c.code_commune
JOIN departement AS d ON c.code_departement = d.code_departement
GROUP BY d.nom_departement
ORDER BY Prix_Moyen_m2 DESC;
"""

# Tu l'exécutes avec read_sql
df_results_average = pd.read_sql(query, con=engine)

# Tu affiches le résultat
display(df_results_average)

          Departement  Prix_Moyen_m2
0               Paris       12077.54
1      Hauts-de-Seine        7374.78
2        Val-de-Marne        5211.45
3     Alpes-Maritimes        4718.68
4   Seine-Saint-Denis        4334.79
..                ...            ...
89           Ardennes        1082.61
90              Meuse        1071.22
91        Haute-Marne        1034.70
92              Indre         889.98
93             Creuse         711.37

[94 rows x 2 columns]

## 5.2 Top 10 des communes par volume de ventes de maisons
L'objectif de cette analyse est de déterminer quelles communes enregistrent le plus grand nombre de mutations pour le type de local "Maison".

**Décomposition de la requête SQL :**
* `SELECT` : On récupère le nom de la ville et on compte le nombre d'entrées dans la table des transactions grâce à la fonction d'agrégation `COUNT(t.id_bien)`.
* `JOIN` : On effectue une chaîne de jointures pour relier la transaction (`t`) à la commune (`c`) en passant par les tables pivots `bien` et `adresse`.
* `WHERE` (La Sous-requête) : C'est la partie stratégique de la requête. Au lieu d'écrire en dur un identifiant (ex: `code_type_local = 1`), on utilise une sous-requête (Subquery) :
    * Le bloc (`SELECT code_type_local FROM type_local WHERE type_local = 'Maison'`) va chercher dynamiquement l'ID correspondant au libellé "Maison". Cela rend le code plus robuste : si l'ID change dans le référentiel, la requête fonctionnera toujours.
* `GROUP BY` : Indispensable pour utiliser `COUNT`, cela permet de regrouper les résultats par nom de commune.
* `ORDER BY ... DESC` : Classement par volume décroissant pour mettre en haut de tableau les villes les plus actives.
* `LIMIT 10£ : On restreint l'affichage aux 10 premiers résultats pour ne conserver que le "Top 10".

In [249]:
query = """
SELECT
    c.nom_commune AS Ville,
    COUNT(t.id_bien) AS Nombre_Ventes
FROM transaction AS t
JOIN bien AS b ON t.id_bien = b.id_bien
JOIN adresse AS a ON b.id_adresse = a.id_adresse
JOIN commune AS c ON a.code_commune = c.code_commune
WHERE b.code_type_local = (
    SELECT code_type_local
    FROM type_local
    WHERE type_local = 'Maison'
)
GROUP BY c.nom_commune
ORDER BY Nombre_Ventes DESC
LIMIT 10;
"""

# Tu l'exécutes avec read_sql
df_results_sales = pd.read_sql(query, con=engine)

# Tu affiches le résultat
display(df_results_sales)

          Departement  Prix_Moyen_m2
0               Paris       12077.54
1      Hauts-de-Seine        7374.78
2        Val-de-Marne        5211.45
3     Alpes-Maritimes        4718.68
4   Seine-Saint-Denis        4334.79
..                ...            ...
89           Ardennes        1082.61
90              Meuse        1071.22
91        Haute-Marne        1034.70
92              Indre         889.98
93             Creuse         711.37

[94 rows x 2 columns]